var data = {
  sections: {
    win10: "Windows 10 Built-In Programs",
    accessibility: "Accessibility",
    audiovideo: "Audio & Video",
    cddvdbr: "CD/DVD/BR",
    development: "Development",
    education: "Education",
    graphics: "Graphics",
    internet: "Internet",
    network: "Network",
    office: "Office",
    productivity: "Producitivity",
    security: "Security",
    utilities: "Utilities (Tools)",
    misc: "Misc.",
    os: "Operating Systems",
    online: "Web-Based Software",
    cheer: ":)",
  },
  section_descriptions: {
    win10: "Just hit the Windows key and start typing in the program's name.",
    cheer: "A small assortment of sites to cheer you up.",
  },
  software: [
    {
      name: "Calculator",
      section: "win10",
      description: "Includes scientific, programmers, etc.",
    },
    {
      name: "Calendar",
      section: "win10",
      description: "A simple calendar for managing your schedule",
    },
    {
      name: "Camera",
      section: "win10",
      description: "Operates your webcam.",
    },
    {
      name: "CD/DVD/BR Burner",
      section: "win10",
      description: "Insert CD/DVD/BD, and you can choose what you want to do.",
    },
    {
      name: "Character Map",
      section: "win10",
      description: "Allows you to find special symbols.",
    },
    {
      name: "Cortana",
      section: "win10",
      description: "Productivity assistant.",
    },
    {
      name: "Ease of Access Center",
      section: "win10",
      description:
        "Magnifier, On-Screen Keyboard, Narrator, High Contrast, etc. (Can be found in the Control Panel)",
    },
    {
      name: "Firewall",
      section: "win10",
      description:
        "A simple firewall for managing inbound and outbound network connections.",
    },
    {
      name: "Groove Music",
      section: "win10",
      description: "Music player and catalog manager.",
    },
    {
      name: "Mail",
      section: "win10",
      description: "Simple e-mail client.",
    },
    {
      name: "Maps",
      section: "win10",
      description:
        "A decent alternative to Google Maps, with a custom implementation of Street View.",
    },
    {
      name: "Math Input Panel",
      section: "win10",
      description: "Whiteboard for mathematicians.",
    },
    {
      name: "Microsoft Edge",
      section: "win10",
      description: "Chromium-based web browser.",
    },
    {
      name: "Night Light",
      section: "win10",
      description:
        "Dims blue light to protect your vision and promote better sleep.",
    },
    {
      name: "Notepad",
      section: "win10",
      description: "Very simple text editor.",
    },
    {
      name: "Paint",
      section: "win10",
      description: "Simplistic graphics editor.",
    },
    {
      name: "Paint 3D",
      section: "win10",
      description:
        "Simplistic graphics editor with basic support for 3D modeling.",
    },
    {
      name: "Photos",
      section: "win10",
      description: "Simple image viewer and catalog manager.",
    },
    {
      name: "Quick Assist",
      section: "win10",
      description: "Screen sharing app.",
    },
    {
      name: "Remote Desktop",
      section: "win10",
      description: "Access Remote PCs.",
    },
    {
      name: "Snip & Sketch",
      section: "win10",
      description: "Screenshotting tool, with support for basic editing.",
    },
    {
      name: "Snipping Tool",
      section: "win10",
      description: "Screenshotting tool. Soon to be replaced by Snip & Sketch.",
    },
    {
      name: "Step Recorder",
      section: "win10",
      description:
        "Troubleshooting tool. Records the actions you took to produce an issue, and outputs them as a .mht file that can be opened with Internet Explorer.",
    },
    {
      name: "Sticky Notes",
      section: "win10",
      description:
        "Note creator and manager, with support for syncing to OneNote.",
    },
    {
      name: "Video Editor",
      section: "win10",
      description: "Basic video editor.",
    },
    {
      name: "Voice Recorder",
      section: "win10",
      description: "Simple recorder for lectures, interviews, etc.",
    },
    {
      name: "Audacity",
      section: "audiovideo",
      description: "Easy-to-use, multi-track audio editor and recorder.",
      link: "https://www.audacityteam.org/",
    },
    {
      name: "Weather",
      section: "win10",
      description: "Weather forecast.",
    },
    {
      name: "Windows Fax & Scan",
      section: "win10",
      description: "A simple interface for faxing and scanning documents.",
    },
    {
      name: "Windows Media Player",
      section: "win10",
      description: "Simple media player for music and videos.",
    },
    {
      name: "Windows Speech Recognition",
      section: "win10",
      description:
        "Allows you to control your PC with your voice. Features a text-to-speech engine.",
    },
    {
      name: "WordPad",
      section: "win10",
      description: "Simple text editor with support for basic markup.",
    },
    {
      name: "Backup",
      section: "win10",
      description: "Backup and restore your computer's data.",
    },
    {
      name: "Reliability History",
      section: "win10",
      description:
        "A simple interface for surveiling any issues your PC has run into.",
    },
    {
      name: "Windows Administrative Tools",
      section: "win10",
      description:
        "A set of useful tools to administer your PC. (Clean-up, defragmentation, event viewer, partitioning, memory check, registry editor, task scheduler, etc.)",
    },
    {
      name: "Windows Task Manager",
      section: "win10",
      description:
        "Allows you to monitor or close currently running applications. (Access with Ctrl+Alt+Del)",
    },
    {
      name: "Godmode",
      section: "win10",
      description:
        "A hidden settings menu with many options. (To access, create a new folder on your Desktop and name it GodMode.{ED7BA470-8E54-465E-825C-99712043E01C})",
    },
    {
      name: "Balbabolka",
      section: "accessibility",
      description: "Text-To-Speech (TTS) Program",
      link: "http://www.cross-plus-a.com/balabolka.htm",
    },
    {
      name: "Dspeech",
      section: "accessibility",
      description: "Text-To-Speech (TTS) Program",
      link: "http://dimio.altervista.org/eng/",
    },
    {
      name: "NaturalReader",
      section: "accessibility",
      description: "Text-To-Speech (TTS) Program",
      link: "https://www.naturalreaders.com/software.html",
    },
    {
      name: "Panopreter",
      section: "accessibility",
      description: "Text-To-Speech (TTS) Program",
      link: "https://www.panopreter.com/en/products/pb/index.php",
    },
    {
      name: "Screen Reader",
      section: "accessibility",
      description:
        "Reads all elements, menus, or text pointed at by the mouse.",
      link: "http://jacquelin.potier.free.fr/screenreader/",
    },
    {
      name: "Workrave",
      section: "accessibility",
      description: "Assists in the recovery and prevention of RSI.",
      link: "https://workrave.org/",
    },
    {
      name: "CCCP",
      section: "audiovideo",
      description: "Audio & Video Codec Pack",
      link: "http://www.cccp-project.net/",
    },
    {
      name: "AIMP",
      section: "audiovideo",
      description:
        "Music player and catalog manager, music format converter, and more.",
      link: "https://www.aimp.ru/",
    },
    {
      name: "Ant Movie Catalog",
      section: "audiovideo",
      description: "Program to manage your collection of movies and tapes.",
      link: "https://antp.be/software/moviecatalog",
    },
    {
      name: "Audacious",
      section: "audiovideo",
      description: "Music player.",
      link: "https://audacious-media-player.org/",
    },
    {
      name: "AudioGrail",
      section: "audiovideo",
      description: "Ultimate audio files toolkit.",
      link: "https://kcsoftwares.com/?kmp3",
    },
    {
      name: "AVI MetaEdit",
      section: "audiovideo",
      description:
        "Tool that supports embedding, validating, and exporting of metadata in AVI (Standard and OpenDML) files.",
      link: "https://mediaarea.net/AVIMetaEdit/",
    },
    {
      name: "Avidemux",
      section: "audiovideo",
      description:
        "Video editor designed for simple cutting, filtering and encoding tasks.",
      link: "http://avidemux.sourceforge.net/",
    },
    {
      name: "BWF MetaEdit",
      section: "audiovideo",
      description:
        "Supports embedding, validating, and exporting of metadata in Broadcast WAVE Format (BWF) files.",
      link: "https://mediaarea.net/BWFMetaEdit/",
    },
    {
      name: "CamStudio",
      section: "audiovideo",
      description: "Desktop recording and streaming software.",
      link: "https://camstudio.org/",
    },
    {
      name: "Cdex",
      section: "audiovideo",
      description: "Open source digital audio CD extractor.",
      link: "https://cdex.mu/",
    },
    {
      name: "DV Analyzer",
      section: "audiovideo",
      description:
        "Examines DV streams in order to report errors in the tape-to-file transfer process.",
      link: "https://mediaarea.net/DVAnalyzer/",
    },
    {
      name: "DVRescue",
      section: "audiovideo",
      description:
        "A set of tools and procedures for migrating data from DV tapes into digital files.",
      link: "https://mediaarea.net/DVRescue/",
    },
    {
      name: "Filmotech",
      section: "audiovideo",
      description: "Movie catalog software.",
      link: "https://www.filmotech.info/",
    },
    {
      name: "foobar2000",
      section: "audiovideo",
      description: "Versatile music player and catalog manager.",
      link: "https://www.foobar2000.org/",
    },
    {
      name: "fre:ac",
      section: "audiovideo",
      description: "Extract, convert, and encode audio.",
      link: "https://www.freac.org/",
    },
    {
      name: "Gom",
      section: "audiovideo",
      description: "Video player.",
      link: "https://www.gomlab.com/",
    },
    {
      name: "Handbrake",
      section: "audiovideo",
      description: "Powerful video transcoder.",
      link: "https://handbrake.fr/",
    },
    {
      name: "K-Lite Codec Pack",
      section: "audiovideo",
      description: "Audio & video codec pack.",
      link: "https://codecguide.com/",
    },
    {
      name: "Kodi",
      section: "audiovideo",
      description: "Open source home theater software.",
      link: "https://kodi.tv/",
    },
    {
      name: "LameXP",
      section: "audiovideo",
      description: "Audio encoder front-end.",
      link: "http://lamexp.sourceforge.net/",
    },
    {
      name: "LAV Filters",
      section: "audiovideo",
      description: "Media splitter/decoder (advanced subtitles configuration).",
      link: "https://www.videohelp.com/software/LAV-Filters",
    },
    {
      name: "LMMS (Linux MultiMedia Studio)",
      section: "audiovideo",
      description:
        "Open source, cross-platform digital audio workstation (DAW).",
      link: "https://sourceforge.net/projects/lmms/",
    },
    {
      name: "Media Player Classic - Black Edition (MPC-BE)",
      section: "audiovideo",
      description: "Open source audio & video player.",
      link: "https://sourceforge.net/projects/mpcbe/",
    },
    {
      name: "Media Player Classic - Home Cinema (MPC-HC)",
      section: "audiovideo",
      description: "Open source audio & video player.",
      link: "https://mpc-hc.org/",
    },
    {
      name: "MediaConch",
      section: "audiovideo",
      link: "https://mediaarea.net/MediaConch",
      description:
        "Implementation checker, policy checker, reporter, and fixer that targets preservation-level audiovisual files.",
    },
    {
      name: "MediaInfo",
      section: "audiovideo",
      description:
        "Convenient unified display of the most relevant technical and tag data for video and audio files.",
      link: "https://mediaarea.net/en/MediaInfo",
    },
    {
      name: "MediaMonkey",
      section: "audiovideo",
      description: "Music and video suite.",
      link: "https://www.mediamonkey.com/",
    },
    {
      name: "Mixxx",
      section: "audiovideo",
      description:
        "Integrates the tools that DJs need to perform creative live mixes with digital music files.",
      link: "https://www.mixxx.org/",
    },
    {
      name: "MOV MetaEdit",
      section: "audiovideo",
      description:
        "Tool that supports the embedding and editing of metadata in MOV and MP4 files.",
      link: "https://mediaarea.net/MOVMetaEdit",
    },
    {
      name: "mp3DirectCut",
      section: "audiovideo",
      description: "MP3 editor and recorder.",
      link: "https://mpesch3.de",
    },
    {
      name: "Mp3Tag",
      section: "audiovideo",
      description: "MP3 tag (metadata) editor.",
      link: "https://www.mp3tag.de/en/",
    },
    {
      name: "MuseScore",
      section: "audiovideo",
      description: "Create, play and print beautiful sheet music.",
      link: "https://musescore.org/en",
    },
    {
      name: "MusicBee",
      section: "audiovideo",
      description: "Music manager and player.",
      link: "https://getmusicbee.com",
    },
    {
      name: "MusicBrainz Picard",
      section: "audiovideo",
      description: "Cross-platform music tagger written in Python.",
      link: "https://picard.musicbrainz.org/",
    },
    {
      name: "OBS Studio",
      section: "audiovideo",
      description:
        "Free and open-source software for video recording and live streaming.",
      link: "https://obsproject.com",
    },
    {
      name: "OpenShot",
      section: "audiovideo",
      description: "Video editor.",
      link: "https://www.openshot.org",
    },
    {
      name: "Plex",
      section: "audiovideo",
      description: "Client-server media player system.",
      link: "https://www.plex.tv/",
    },
    {
      name: "PotPlayer",
      description: "Multimedia player.",
      section: "audiovideo",
      link: "https://potplayer.daum.net/",
    },
    {
      name: "QCTools",
      section: "audiovideo",
      description:
        "Helps users analyze and understand their digitized video files through use of audiovisual analytics and filtering.",
      link: "https://mediaarea.net/QCTools",
    },
    {
      name: "Qmmp",
      section: "audiovideo",
      description: "Qt-based multimedia player.",
      link: "https://sourceforge.net/projects/qmmp-dev",
    },
    {
      name: "SMPlayer",
      section: "audiovideo",
      description: "Free media player with built-in codecs.",
      link: "https://www.smplayer.info",
    },
    {
      name: "TAudioConverter",
      section: "audiovideo",
      description: "Audio converter and extractor.",
      link: "https://www.videohelp.com/software/TAudioConverter",
    },
    {
      name: "TEncoder Video Converter",
      section: "audiovideo",
      description: "Multi-threaded multimedia (video and audio) converter.",
      link: "https://www.fosshub.com/TEncoder-Video-Converter.html",
    },
    {
      name: "VirtualDub",
      section: "audiovideo",
      description: "Video capture/processing utility.",
      link: "http://www.virtualdub.org/",
    },
    {
      name: "VLC Media Player",
      section: "audiovideo",
      description: "Widely popular media player with support for many formats.",
      link: "https://www.videolan.org/vlc/index.en-GB.html",
    },
    {
      name: "WaveShop",
      section: "audiovideo",
      description: "Audio editor.",
      link: "http://waveshop.sourceforge.net/",
    },
    {
      name: "wxMP3gain",
      section: "audiovideo",
      description: "MP3 audio normalizer.",
      link: "https://sourceforge.net/projects/wxmp3gain/",
    },
    {
      name: "XMPlay",
      section: "audiovideo",
      description: "Audio player and library.",
      link: "https://www.un4seen.com/",
    },
    {
      name: "Ashampoo® Burning Studio FREE",
      section: "cddvdbr",
      description: "Burn, copy, and rip CD, DVD, and Blu-Ray discs.",
      link:
        "https://www.ashampoo.com/en/usd/pin/7110/burning-software/burning-studio-free",
    },
    {
      name: "CDBurnerXP",
      section: "cddvdbr",
      description: "CD, DVD, ISO, HD-DVD, and Blu-Ray burning software.",
      link: "https://cdburnerxp.se/en/home",
    },
    {
      name: "cdrtfe",
      section: "cddvdbr",
      description: "Open-source CD, DVD, and Blu-Ray burning application.",
      link: "https://cdrtfe.sourceforge.io/",
    },
    {
      name: "DaVinci Resolve",
      section: "cddvdbr",
      description: "Video editing software.",
      link: "https://www.blackmagicdesgin.com/uk/products/davinciresolve/",
    },
    {
      name: "DVDStyler",
      section: "cddvdbr",
      description: "DVD authoring application.",
      link: "https://www.dvdstyler.org/en/",
    },
    {
      name: "Ignition",
      section: "cddvdbr",
      description: "CD/DVD burning optimizer.",
      link: "https://kcsoftwares.com/?ignition",
    },
    {
      name: "ImgBurn",
      section: "cddvdbr",
      description:
        "Lightweight CD, DVD, HD-DVD, and Blu-Ray burning application.",
      link: "https://www.imgburn.com/",
    },
    {
      name: "WinCDEmu",
      section: "cddvdbr",
      description: "Open-source CD, DVD, and Blu-Ray emulator.",
      link: "https://wincdemu.sysprogs.org/",
    },
    {
      name: "AkelPad",
      section: "development",
      description: "Open-source editor for plain text.",
      link: "http://akelpad.sourceforge.net/en/index.php",
    },
    {
      name: "Atom",
      section: "development",
      description: "A hackable text editor.",
      link: "https://atom.io",
    },
    {
      name: "ATPad",
      section: "development",
      description: "Text editor.",
      link: "http://atpad.sourceforge.net/index.php?page=1",
    },
    {
      name: "Cppcheck",
      section: "development",
      description: "Static analysis tool for C/C++ code.",
      link: "http://cppcheck.sourceforge.net/",
    },
    {
      name: "DB Browser for SQLite",
      section: "development",
      description:
        "High quality, visual, open-source tool to create, design, and edit database files compatible with SQLite.",
      link: "https://sqlitebrowser.org",
    },
    {
      name: "DocPad",
      section: "development",
      description: "Text editor.",
      link: "https://www.gammadyne.com/docpad.htm",
    },
    {
      name: "EditPad Lite",
      section: "development",
      description: "Text editor.",
      link: "https://www.editpadlite.com/",
    },
    {
      name: "FluentNotepad",
      section: "development",
      description: "Text editor.",
      link:
        "https://www.deviantart.com/salvog92/art/FluentNotepad-RC-171637273",
    },
    {
      name: "Free HTML Editor",
      section: "development",
      description: "Free HTML editor.",
      link: "https://www.coffeecup.com/free-editor/",
    },
    {
      name: "Frhed",
      section: "development",
      description: "Free hex editor",
      link: "http://frhed.sourceforge.net/en/",
    },
    {
      name: "Geany",
      section: "development",
      description:
        "Powerful, stable, and lightweight text editor for programmers.",
      link: "https://www.geany.org",
    },
    {
      name: "GetDiz",
      section: "development",
      description: "Text editor.",
      link: "https://www.outertech.com/en/replacement-for-notepad",
    },
    {
      name: "HM NIS Edit",
      section: "development",
      description: "Editor/IDE for NSIS.",
      link: "http://hmne.sourceforge.net/index.php",
    },
    {
      name: "IniTranslator",
      link: "https://sourceforge.net/projects/initranslator",
      section: "development",
      description: ".ini trasnlator tool.",
    },
    {
      name: "Notepad++",
      description: "Free source code editor and notepad replacement.",
      section: "development",
      link: "https://notepad-plus-plus.org/",
    },
    {
      name: "Notepad2",
      section: "development",
      description:
        "Lightweight, Notepad-like text editor with syntax highlighting.",
      link: "http://www.flos-freeware.ch/notepad2.html",
    },
    {
      name: "NoteTab Light",
      section: "development",
      description: "Text editor.",
      link: "https://www.notetab.com/notetab-light.php",
    },
    {
      name: "NSIS",
      section: "development",
      description:
        "Professional open-source system to create Windows installers.",
      link: "https://nsis.sourceforge.io/Main_Page",
    },
    {
      name: "PSPad",
      section: "development",
      description: "Text editor.",
      link: "http://www.paspad.com/",
    },
    {
      name: "Q-Eye",
      description: "QVD and QVX files editor.",
      link: "https://www.etl-tools.com/q-eye/overview.html",
      section: "development",
    },
    {
      name: "QOwnNotes",
      description: "Cross-platform, open-source notepad for plain-text files.",
      section: "development",
      link: "https://www.qownnotes.org/",
    },
    {
      name: "Sublime Text",
      description: "A sophisticated text editor.",
      section: "development",
      link: "https://www.sublimetext.com/",
    },
    {
      name: "TED Notepad",
      description: "Text editor.",
      section: "development",
      link: "http://jsimlo.sk/notepad/",
    },
    {
      name: "Visual Studio Express",
      description: "Set of integrated development environments.",
      section: "development",
      link: "https://visualstudio.microsoft.com/vs/express/",
    },
    {
      name: "XAMPP",
      description:
        "Free, easy-to-install Apache distribution containing MariaDB, PHP, and Perl.",
      section: "development",
      link: "https://www.apachefriends.org/index.html",
    },
    {
      name: "Anki",
      section: "education",
      description: "Powerful, intelligent flash cards.",
      link: "https://apps.ankiweb.net/",
    },
    {
      name: "Artha",
      description: "Thesaurus based on WordNet.",
      section: "education",
      link: "https://sourceforge.net/projects/artha/",
    },
    {
      name: "BOINC",
      section: "education",
      description:
        "While your PC is idle, BOINC can utilize it to help scientific research.",
      link: "https://boinc.berkeley.edu/",
    },
    {
      name: "BPBible",
      section: "education",
      description: "Bible study tool.",
      link: "https://github.com/bpbible/bpbible",
    },
    {
      name: "Bricklink",
      section: "education",
      description: "Build, render, and create Lego instructions.",
      link: "https://www.bricklink.com/v2/build/studio.page",
    },
    {
      name: "Celestia",
      section: "education",
      description: "The free space simulation.",
      link: "https://celestia.space/",
    },
    {
      name: "DripTray",
      section: "education",
      description: "Better diabetes monitoring with a CGM.",
      link: "https://www.zhornsoftware.co.uk/driptray/index.html",
    },
    {
      name: "FreeMat",
      section: "education",
      description:
        "Free environment for rapid engineering, scientific prototyping, and data processing.",
      link: "http://freemat.sourceforge.net/",
    },
    {
      name: "GoldenDict",
      description: "Feature-rich dictionary lookup program.",
      section: "education",
      link: "http://goldendict.org/",
    },
    {
      name: "Gramps",
      description: "Powerful genalogical research software.",
      section: "education",
      link: "https://gramps-project.org/blog/",
    },
    {
      name: "Kidlogger",
      description: "Parental time control software.",
      section: "education",
      link: "http://kidlogger.net/",
    },
    {
      name: "Legacy",
      description: "Genealogy software.",
      section: "education",
      link: "https://legacyfamilytree.com/DownloadLegacy.asp",
    },
    {
      name: "Mnemosyne",
      description: "Flashcard memorization program.",
      section: "education",
      link: "https://mnemosyne-proj.org/",
    },
    {
      name: "NASA World Wind",
      section: "education",
      description: "Open-source virtual globe.",
      link: "https://worldwind.arc.nasa.gov/",
    },
    {
      name: "R",
      section: "education",
      description:
        "Software environment for statistical computing and graphics.",
      link: "https://www.r-project.org/",
    },
    {
      name: "Solfege",
      section: "education",
      description: "Ear training software.",
      link: "https://sourceforge.net/projects/solfege/",
    },
    {
      name: "Space Engine",
      section: "education",
      description: "Realistic virutal unvierse.",
      link: "http://spaceengine.org/",
    },
    {
      name: "Stellarium",
      section: "education",
      description: "Free, open-source planetarium.",
      link: "https://stellarium.org/en/",
    },
    {
      name: "TIPP10",
      section: "education",
      description:
        "Touch typing tutor with both an online and offline version.",
      link: "https://www.tipp10.com/en/",
    },
    {
      name: "TypeFaster",
      section: "education",
      description: "Touch typing tutor.",
      link: "https://sourceforge.net/projects/typefaster/",
    },
    {
      name: "AndreaMosaic",
      section: "graphics",
      description:
        "Project to create digital art using images and computer software.",
      link: "http://www.andreaplanet.com/andreamosaic/",
    },
    {
      name: "Blender",
      description:
        "Open-source tool for 3D modelling, animation, rendering, post-production, and playback.",
      section: "graphics",
      link: "https://www.blender.org",
    },
    {
      name: "Caesium",
      description: "Image optimizer and converter.",
      section: "graphics",
      link: "https://github.com/Lymphatus/caesium-image-compressor",
    },
    {
      name: "ColorPic",
      description: "Color picker.",
      section: "graphics",
      link: "http://www.iconico.com/colorpic/",
    },
    {
      name: "Colour Contrast Analyser",
      description: "Analayze color contrast and readability.",
      section: "graphics",
      link: "https://developer.paciellogroup.com/resources/contrastanalyser/",
    },
    {
      name: "Cornice",
      description: "Cross-platform image viewer.",
      section: "graphics",
      link: "http://wxglade.sourceforge.net/extra/cornice.html",
    },
    {
      name: "darktable",
      description: "Photography workflow application and RAW developer.",
      section: "graphics",
      link: "https://www.darktable.org/",
    },
    {
      name: "Dia",
      description: "Program to draw structured diagrams.",
      section: "graphics",
      link: "https://dia-installer.de/",
    },
    {
      name: "DiffImg",
      description: "Simple image comparison tool.",
      section: "graphics",
      link: "https://sourceforge.net/projects/diffimg/",
    },
    {
      name: "FastStone Capture",
      section: "graphics",
      description: "Screen capture tool and screen video recorder.",
      link: "https://www.faststone.org/index.htm",
    },
    {
      name: "FastStone Image Viewer",
      section: "graphics",
      description:
        "Fast, stable, user-friendly image browser, converter, and editor.",
      link: "https://www.faststone.org/index.htm",
    },
    {
      name: "FastStone Photo Reszier",
      section: "graphics",
      description: "Image resizer.",
      link: "https://www.faststone.org/",
    },
    {
      name: "ffdshow",
      description: "Codec pack.",
      section: "graphics",
      link: "https://sourceforge.net/projects/ffdshow-tryout/",
    },
    {
      name: "Fotografix",
      description: "Free image editor.",
      section: "graphics",
      link: "https://lmadhavan.com/fotografix/",
    },
    {
      name: "Fotor",
      description: "Photo editing software.",
      section: "graphics",
      link: "https://www.fotor.com/windows/index.html",
    },
    {
      name: "FotoSketcher",
      description: "Turns digital images into art.",
      section: "graphics",
      link: "https://fotosketcher.com/",
    },
    {
      name: "FreeCAD",
      description: "3D parametric modeler",
      link: "https://www.freecadweb.org/",
      section: "graphics",
    },
    {
      name: "Fyre",
      description: "Tool for producing computational artwork.",
      link: "http://fyre.navi.cx/about.shtml",
      section: "graphics",
    },
    {
      name: "GIMP",
      description:
        "Open-source photo and image editor; the most robust free altenative to Photoshop.",
      link: "https://www.gimp.org/",
      section: "graphics",
    },
    {
      name: "Greenfish Icon Editor Pro",
      description: "Image editor, icon/cursor/animation creator.",
      link: "http://greenfishsoftware.org/gfie.php",
      section: "graphics",
    },
    {
      name: "Greenshot",
      description: "Screenshot tool.",
      link: "https://getgreenshot.org/",
      section: "graphics",
    },
    {
      name: "HitFilm Express",
      description: "Video editing software.",
      link: "https://fxhome.com/hitfilm-express",
      section: "graphics",
    },
    {
      name: "Hot Spot Studio",
      description: "Freeware toy that lets you create stunning images.",
      link: "https://rlvision.com/spots/about.php",
      section: "graphics",
    },
    {
      name: "IDPhotoStudio",
      description: "User-friendly ID photo duplicator and printer.",
      link: "https://www.kcsoftwares.com/?idps",
      section: "graphics",
    },
    {
      name: "Inkscape",
      description: "Vector imagery editing software.",
      link: "https://inkscape.org/",
      section: "graphics",
    },
    {
      name: "IrfanView",
      description:
        "Lightweight graphic viewer, editor, organizer, and bulk converter.",
      link: "https://www.irfanview.com/",
      section: "graphics",
    },
    {
      name: "JPEGView",
      description: "Fast and highly configurable viewer/editor.",
      link: "https://sourceforge.net/projects/jpegview/",
      section: "graphics",
    },
    {
      name: "K-3D",
      description: "3D modeling and animation software.",
      link: "https://www.k-3d.org/",
      section: "graphics",
    },
    {
      name: "Krita",
      description: "Painting program.",
      link: "https://krtia.org/en/",
      section: "graphics",
    },
    {
      name: "LazPaint",
      description: "Image editor.",
      link: "https://sourceforge.net/projects/lazpaint/",
      section: "graphics",
    },
    {
      name: "LibreCAD",
      description: "2D computer-aided design (CAD) tool.",
      link: "https://librecad.org/",
      section: "graphics",
    },
    {
      name: "Lightscreen",
      description: "Screenshot tool.",
      link: "https://lightscreen.com.ar/",
      section: "graphics",
    },
    {
      name: "LightWorks",
      description: "Video creation package.",
      link: "https://www.lwks.com/",
      section: "graphics",
    },
    {
      name: "MyPaint",
      description: "Painting and illustration software.",
      link: "http://mypaint.org/",
      section: "graphics",
    },
    {
      name: "OpenSCAD",
      description: "Software for creating solid 3D CAD objects.",
      link: "http://www.openscad.org/",
      section: "graphics",
    },
    {
      name: "Paint.net",
      description:
        "Photo editing software, mid-way in complexity between MS Paint and GIMP.",
      link: "https://www.getpaint.net/index.html",
      section: "graphics",
    },
    {
      name: "Pencil Project",
      description: "Prototyping and diagramming tool.",
      link: "https://pencil.evolus.vn/",
      section: "graphics",
    },
    {
      name: "Pencil2D",
      description: "Intuitive tool for making 2D, hand-drawn animations.",
      link: "https://www.pencil2d.org/",
      section: "graphics",
    },
    {
      name: "PhotoFilmStrip",
      description: "Photo slideshow creator.",
      link: "https://www.photofilmstrip.org/en/",
      section: "graphics",
    },
    {
      name: "PhotoFiltre",
      description: "Image retouching program.",
      link: "http://www.photofiltre-studio.com/pf7-en.htm",
      section: "graphics",
    },
    {
      name: "PicPick",
      description: "Screen capture, editor, color picker, and more.",
      link: "https://picpick.app/en/",
      section: "graphics",
    },
    {
      name: "PngOptimizer",
      description: "Image optimizer and converter.",
      link: "https://psydk.org/pngoptimizer",
      section: "graphics",
    },
    {
      name: "RawTherappe",
      description: "Cross-platform raw image processing program.",
      link: "https://rawtherappe.com/",
      section: "graphics",
    },
    {
      name: "ShareX",
      description: "Screen capture and file sharing.",
      link: "https://getsharex.com/",
      section: "graphics",
    },
    {
      name: "Shark007 Video Codec Pack",
      description: "Codec pack.",
      link: "http://shark007.net/index.html",
      section: "graphics",
    },
    {
      name: "Shotcut",
      description: "Video editing software.",
      link: "https://shotcut.org/",
      section: "graphics",
    },
    {
      name: "Vectr",
      description: "Vector graphics software.",
      link: "https://vectr.com/",
      section: "graphics",
    },
    {
      name: "VideoInspector",
      description:
        "Provides you with as much information as possible about your video files.",
      link: "https://kcsoftwares.com/?vtb",
      section: "graphics",
    },
    {
      name: "X Codec Pack",
      description: "Codec pack.",
      link: "https://www.xcodecpack.com/",
      section: "graphics",
    },
    {
      name: "XnView",
      description: "Image resizer, batch image converter, and more.",
      link: "https://www.xnview.com/en/",
      section: "graphics",
    },
    {
      name: "Chrome",
      description: "Fast, simple, and themeable browser.",
      link: "https://www.google.com/chrome/",
      section: "internet",
    },
    {
      name: "Discord",
      description: "Video, audio, and text communication platform.",
      link: "https://discord.com/",
      section: "internet",
    },
    {
      name: "Ekiga",
      description: "Softphone, video conferencing, and chat.",
      link: "https://www.ekiga.org/",
      section: "internet",
    },
    {
      name: "Falkon",
      description: "KDE web browser using QtWebEngine.",
      link: "https://www.falkon.org",
      section: "internet",
    },
    {
      name: "Firefox",
      description: "Fast, open-source web browser.",
      link: "https://www.mozilla.org/en-GB/",
      section: "internet",
    },
    {
      name: "Free Download Manager",
      description: "Download manager and optimizer.",
      link: "https://freedownloadmanager.org/",
      section: "internet",
    },
    {
      name: "gPodder",
      description: "Podcast receiver and manager.",
      link: "https://gpodder.github.io/",
      section: "internet",
    },
    {
      name: "HexChat",
      description: "IRC chat client.",
      link: "https://hexchat.github.io/",
      section: "internet",
    },
    {
      name: "Instantbird",
      description: "Instant messaging on AOL, Facebook, Google, MSN, and more.",
      link: "http://instantbird.com/",
      section: "internet",
    },
    {
      name: "Isotoxin",
      description: "Multiprotocol manager.",
      link: "https://github.com/isotoxin/isotoxin",
      section: "internet",
    },
    {
      name: "Juice",
      description: "Podcast receiver and manager.",
      link: "http://juicereceiver.sourceforge.net/",
      section: "internet",
    },
    {
      name: "K-Meleon",
      description: "Fast, customizable, lightweight web browser.",
      section: "internet",
      link: "https://kmeleonbrowser.org/",
    },
    {
      name: "KVIrc",
      description: "IRC chat client.",
      section: "internet",
      link: "https://www.kvirc.net/",
    },
    {
      name: "Maxthon",
      description: "Web browser.",
      section: "internet",
      link: "https://www.maxthon.com/",
    },
    {
      name: "MediaHuman Youtube to MP3 Converter",
      description:
        "Download and convert Youtube videos to MP3s with one click.",
      link: "https://www.mediahuman.com/",
      section: "internet",
    },
    {
      name: "MicroSIP",
      description: "Lightweight SIP softphone.",
      link: "https://www.microsip.org/",
      section: "internet",
    },
    {
      name: "Mumble",
      description:
        "Free, open-source, low-latency, high-quality voice chat application.",
      link: "https://www.mumble.info/",
      section: "internet",
    },
    {
      name: "Opera",
      description: "Internet browser.",
      link: "https://www.opera.com/",
      section: "internet",
    },
    {
      name: "Opera GX",
      description: "Gaming-oriented web browser.",
      link: "https://www.opera.com/gx",
      section: "internet",
    },
    {
      name: "Pidgin",
      description: "Universal chat client.",
      link: "https://pidgin.im/",
      section: "internet",
    },
    {
      name: "PopMan",
      description: "Simple and lightweight email client.",
      link: "http://www.ch-software.de/popman/index.html",
      section: "internet",
    },
    {
      name: "qBittorrent",
      description: "Bittorrent client.",
      link: "https://www.qubittorrent.org/",
      section: "internet",
    },
    {
      name: "QuiteRSS",
      description: "Standalone RSS feed reader.",
      link: "https://quiterss.org/",
      section: "internet",
    },
    {
      name: "RSSOwl",
      description: "Organize, search, and read all your news feeds.",
      link: "http://www.rssowl.org",
      section: "internet",
    },
    {
      name: "SeaMonkey",
      description: "All-in-one Internet application suite.",
      link: "http://www.seamonkey-project.org/",
      section: "internet",
    },
    {
      name: "Skype",
      description: "Video and audio conferncing tool.",
      link: "https://www.skype.com/",
      section: "internet",
    },
    {
      name: "SRWare Iron",
      description: "Advanced web browser.",
      link: "https://www.srware.net/iron/",
      section: "internet",
    },
    {
      name: "Sylpheed",
      description: "Lightweight and user-friendly e-mail client.",
      link: "https://sylpheed.sraoss.jp/en/",
      section: "internet",
    },
    {
      name: "Teamspeak",
      description: "VoIP communication system.",
      link: "https://www.teamspeak.com/",
      section: "internet",
    },
    {
      name: "Telegram Desktop",
      description:
        "Fast and secure desktop app, perfectly synced with your mobile phone.",
      link: "https://desktop.telegram.org/",
      section: "internet",
    },
    {
      name: "ThunderBird",
      description: "Email application.",
      link: "https://www.thunderbird.net/en-GB/",
      section: "internet",
    },
    {
      name: "Tor",
      description: "Anonymous web browser built off of Mozilla Firefox.",
      link: "https://www.torproject.org/",
      section: "internet",
    },
    {
      name: "Transmission",
      description: "Lightweight bittorrent client.",
      link: "https://transmissionbt.com/",
      section: "internet",
    },
    {
      name: "TunnelBear",
      description: "VPN.",
      link: "https://www.tunnelbear.com/",
      section: "internet",
    },
    {
      name: "TweeDeck",
      description: "Twitter client.",
      link: "https://tweetdeck.twitter.com/",
      section: "internet",
    },
    {
      name: "WackGet",
      description: "Simple download manager.",
      link: "https://github.com/MammothAU/WackGet",
      section: "internet",
    },
    {
      name: "WinWGet",
      description: "GUI for WackGet.",
      link: "http://winwget.sourceforge.net/",
      section: "internet",
    },
    {
      name: "µTorrent",
      description: "Ad-supported bittorrent client.",
      link: "https://www.utorrent.com/",
      section: "internet",
    },
    {
      name: "ApHeMo",
      description: "Health monitoring analyzer for Apache HTTP Server.",
      link: "https://kcsoftwares.com/?aphemo",
      section: "network",
    },
    {
      name: "dot11Experet",
      description: "Troubleshooting software for your WLAN.",
      link: "https://kcsoftwares.com/?dot11expert",
      section: "network",
    },
    {
      name: "FileZilla",
      description: "FTP client.",
      link: "https://filezilla-project.org/",
      section: "network",
    },
    {
      name: "KiTTY",
      description: "Telnet and SSH client based on PuTTY.",
      link: "http://www.9bis.net/kitty/#!index.md",
      section: "network",
    },
    {
      name: "PuTTY",
      description: "Telnet and SSH client.",
      link: "https://www.chiark.greenend.org.uk/~sgtatham/putty/",
      section: "network",
    },
    {
      name: "SmarTTY",
      description: "Multi-tabbed SSH client with SCP support.",
      link: "https://sysprogs.com/SmarTTY/",
      section: "network",
    },
    {
      name: "Spiceworks",
      description: "Simple, easy-to-use website monitoring software.",
      link:
        "https://www.spiceworks.com/free-network-monitoring-management-software/",
      section: "network",
    },
    {
      name: "WiFi Inspector",
      description: "Real time monitoring of wireless network status.",
      link:
        "https://www.cambiumnetworks.com/products/software/wifi-designer-and-wifi-inspector/",
      section: "network",
    },
    {
      name: "WiFi Scanner",
      description: "WiFi information in real time.",
      link:
        "https://www.acrylicwifi.com/en/wlan-wifi-wireless-network-software-tools/wlan-scanner-acrylic-wifi-free/",
      section: "network",
    },
    {
      name: "WinSCP",
      description: "SFTP client and FTP client",
      link: "https://winscp.net/eng/index.php",
      section: "network",
    },
    {
      name: "ZMeter",
      description: "Show Network, CPU, RAM and Disk in a desktop graph.",
      link: "https://www.zhornsoftware.co.uk/zmeter/index.html",
      section: "network",
    },
    {
      name: "Apache OpenOffice",
      description: "Word processor, spreadsheet, presentations.",
      link: "https://www.openoffice.org/",
      section: "office",
    },
    {
      name: "calibre",
      description: "Ebook manager and viewer",
      link: "https://calibre-ebook.com/",
      section: "office",
    },
    {
      name: "Cherrytree",
      description: "Hierarchical note-taker and organizer.",
      link: "https://www.giuspen.com/cherrytree/",
      section: "office",
    },
    {
      name: "CintaNotes",
      description: "Lightweight note-taker.",
      link: "http://cintanotes.com/",
      section: "office",
    },
    {
      name: "CuteMarkEd",
      description: "Simple markdown editor.",
      link: "https://cloose.github.io/CuteMarkEd/",
      section: "office",
    },
    {
      name: "Diffpdf",
      description: "Compare two PDF files – textually or visually.",
      link: "http://www.qtrac.eu/diffpdf.html",
      section: "office",
    },
    {
      name: "Finance Explorer",
      description: "Easy to use personal finance software.",
      link: "https://www.metalogicsw.com/financeexplorer/",
      section: "office",
    },
    {
      name: "FocusWriter",
      description: "A simple, distraction-free writing environment.",
      link: "https://gottcode.org/focuswriter/",
      section: "office",
    },
    {
      name: "Foxit Reader",
      description: "Small, fast, and feature-rich PDF reader.",
      link: "https://www.foxitsoftware.com/pdf-reader/",
      section: "office",
    },
    {
      name: "Free PDF Printer",
      description: "PDF printer.",
      link: "https://www.bullzip.com/products/pdf/info.php",
      section: "office",
    },
    {
      name: "Gnumeric",
      description: "Spreadsheet software.",
      link: "http://www.gnumeric.org/",
      section: "office",
    },
    {
      name: "Google Keep",
      description: "Cross-platform note taker.",
      link: "https://www.google.com/keep/",
      section: "office",
    },
    {
      name: "Jarte",
      description: "Lightweight, tabbed word processor.",
      link: "https://www.jarte.com/",
      section: "office",
    },
    {
      name: "K-ML",
      description: "Mailing list / newsletter manager.",
      link: "https://kcsoftwares.com/?kml",
      section: "office",
    },
    {
      name: "LaTeX",
      description: "Document preparation software.",
      link: "https://www.latex-project.org/",
      section: "office",
    },
    {
      name: "LibreOffice",
      description:
        "Word processor, spreadsheet, presentations with excellent compatibility.",
      link: "https://www.libreoffice.org/",
      section: "office",
    },
    {
      name: "MassCert",
      description: "User-friendly batch digital signature utility.",
      link: "https://kcsoftwares.com/?masscert",
      section: "office",
    },
    {
      name: "NAPS2",
      description:
        "Scan documents to PDF and other file types, as simply as possible.",
      link: "https://www.naps2.com/",
      section: "office",
    },
    {
      name: "Nitro PDF Reader",
      description: "PDF reader.",
      link: "https://www.gonitro.com/pdf-reader",
      section: "office",
    },
    {
      name: "Notebook",
      description: "Note taker.",
      link: "https://www.zoho.com/notebook/",
      section: "office",
    },
    {
      name: "PDF Studio",
      description: "Merge, move, copy, and delete pages in your PDF document.",
      link: "https://www.bullzip.com/products/stu/",
      section: "office",
    },
    {
      name: "PDFCreator",
      description: "PDF creator and converter.",
      link: "https://www.pdfforge.org/pdfcreator",
      section: "office",
    },
    {
      name: "PDFtk",
      description: "PDF toolkit.",
      link: "https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/",
      section: "office",
    },
    {
      name: "PDFTK Builder",
      description:
        "Split, collate, watermark and password protect PDF documents.",
      link: "http://www.angusj.com/pdftkb/",
      section: "office",
    },
    {
      name: "PNotes",
      description: "Sticky notes.",
      link: "https://pnotes-1932d.firebaseapp.com/home",
      section: "office",
    },
    {
      name: "PrinterShare",
      description: "Share your printer with anyone you want.",
      link: "http://www.printershare.com/",
      section: "office",
    },
    {
      name: "RedNotebook",
      description: "Desktop journal and diary.",
      link: "https://rednotebook.sourceforge.io/",
      section: "office",
    },
    {
      name: "Scribus",
      description: "Open-source desktop publishing.",
      link: "https://www.scribus.net/",
      section: "office",
    },
    {
      name: "Sigil",
      description: "Multi-platform EPUB e-book editor.",
      link: "https://sigil-ebook.com/",
      section: "office",
    },
    {
      name: "Simplenote",
      description: "Cross-platform note taker.",
      link: "https://simplenote.com/",
      section: "office",
    },
    {
      name: "SpeedCrunch",
      description: "High-precision scientific calculator",
      link: "https://speedcrunch.org/",
      section: "office",
    },
    {
      name: "Stickies",
      description: "Lightweight sticky notes.",
      link: "https://www.zhornsoftware.co.uk/stickies/index.html",
      section: "office",
    },
    {
      name: "Sumatra PDF",
      description:
        "Lightweight editor for PDF, ePub, MOBI, and many other formats.",
      link: "https://www.sumatrapdfreader.org/free-pdf-reader.html",
      section: "office",
    },
    {
      name: "Task Coach",
      description: "Simple, open-source todo manager",
      link: "https://www.taskcoach.org/",
      section: "office",
    },
    {
      name: "The Guide",
      description: "Two-panel extrinsic outliner.",
      link: "http://theguide.sourceforge.net/",
      section: "office",
    },
    {
      name: "TurboCASH",
      description: "Open accounting software.",
      link: "https://www.turbocash.net/",
      section: "office",
    },
    {
      name: "WinDjView",
      description: "Fast, compact and powerful DjVu viewer.",
      link: "https://windjview.sourceforge.io/",
      section: "office",
    },
    {
      name: "WPS Office",
      description:
        "Word processor, spreadsheet, presentations with excellent compatibility.",
      link: "https://wps.com/",
      section: "office",
    },
    {
      name: "ZoomIt",
      description:
        "Screen zoom and annotation tool for technical presentations.",
      link: "https://docs.microsoft.com/en-us/sysinternals/downloads/zoomit",
      section: "office",
    },
    {
      name: "AHT",
      description: "Hide desktop icons away at the top of the screen.",
      link: "https://www.zhornsoftware.co.uk/aht/index.html",
      section: "productivity",
    },
    {
      name: "AquaSnap",
      description: "Tiling window manager.",
      link: "https://www.nurgo-software.com/products/aquasnap",
      section: "productivity",
    },
    {
      name: "AutoHotKey",
      description: "Powerful scripting language for automating tasks.",
      link: "https://www.autohotkey.com/",
      section: "productivity",
    },
    {
      name: "Caffeine",
      description: "Prevent your computer from going to sleep.",
      link: "https://www.zhornsoftware.co.uk/caffeine/index.html",
      section: "productivity",
    },
    {
      name: "CmapTools",
      description: "Mind mapping tool.",
      link: "https://cmap.ihmc.us/cmaptools/",
      section: "productivity",
    },
    {
      name: "Dia",
      description: "A program to draw structured diagrams.",
      link: "http://dia-installer.de/",
      section: "productivity",
    },
    {
      name: "f.lux®",
      desciprtion:
        "Dims blue light to protect your vision and promote better sleep.",
      link: "https://justgetflux.com/",
      section: "productivity",
    },
    {
      name: "Find and Run Robot",
      description: "Quick program launcher.",
      link: "https://www.donationcoder.com/software/mouser/popular-apps/farr",
      section: "productivity",
    },
    {
      name: "FreeMind",
      description: "Mind mapping tool.",
      link: "http://freemind.sourceforge.net/wiki/index.php/Main_Page",
      section: "productivity",
    },
    {
      name: "GnattProject",
      description: "Project management software.",
      link: "https://www.ganttproject.biz/",
      section: "productivity",
    },
    {
      name: "GnuCash",
      description: "Small-business financial-accounting software",
      link: "https://www.gnucash.org/",
      section: "productivity",
    },
    {
      name: "Gridy",
      description: "Snap your open windows to a grid",
      link: "https://sector-seven.com/software/gridy",
      section: "productivity",
    },
    {
      name: "HotkeyP",
      description: "Keyboard, mouse, and gamepad mapper.",
      link: "https://sourceforge.net/projects/hotkeyp/",
      section: "productivity",
    },
    {
      name: "Launchy",
      description: "Simple program launcher.",
      link: "https://www.launchy.net/",
      section: "productivity",
    },
    {
      name: "Money Manager Ex",
      description: "Easy-to-use personal finance software.",
      link: "https://www.moneymanagerex.org/",
      section: "productivity",
    },
    {
      name: "Qiqqa",
      description: "Mind mapping tool.",
      link: "http://www.qiqqa.com/",
      section: "productivity",
    },
    {
      name: "Zotero",
      description:
        "Free, easy-to-use tool to help you collect, organize, cite, and share research.",
      link: "https://www.zotero.org/",
      section: "productivity",
    },
    {
      name: "LiberKey",
      description: "Apps made portable.",
      link: "https://www.liberkey.com/en/",
      section: "misc",
    },
    {
      name: "PortableApps",
      description: "Apps made portable.",
      link: "https://portableapps.com/",
      section: "misc",
    },
    {
      name: "All Free Linux Distros",
      description: "Open-source OS alternative to Windows.",
      link: "https://www.linux.org/",
      section: "os",
    },
    {
      name: "FreeNAS",
      description: "Unified file and block storage, VM, and Docker system.",
      link: "https://www.freenas.org/",
      section: "os",
    },
    {
      name: "Adaware",
      description: "Antivirus software.",
      link: "https://www.adaware.com/free-antivirus-download",
      section: "security",
    },
    {
      name: "AdwCleaner",
      description: "Spyware remover.",
      link: "https://www.malwarebytes.com/adwcleaner/",
      section: "security",
    },
    {
      name: "Avast",
      description: "Antivirus software.",
      link: "https://www.avast.com/",
      section: "security",
    },
    {
      name: "AVG",
      description: "Antivirus software.",
      link: "https://www.avg.com/",
      section: "security",
    },
    {
      name: "Avira",
      description: "Antivirus software.",
      link: "https://www.avira.com/",
      section: "security",
    },
    {
      name: "AxCrypt",
      description: "Encryption tool.",
      link: "https://www.axcrypt.net/",
      section: "security",
    },
    {
      name: "ClamWin",
      description: "Open-source antivirus software.",
      link: "http://www.clamwin.com/",
      section: "security",
    },
    {
      name: "Crypto Stuff",
      description: "Portable cryptography software.",
      link: "http://jacquelin.potier.free.fr/CryptoStuff/",
      section: "security",
    },
    {
      name: "Eraser",
      description: "A security tool to remove sensitive data from your HDD.",
      link: "https://eraser.heidi.ie/",
      section: "security",
    },
    {
      name: "IObit Malware Fighter",
      description: "Anti-malware and privacy locking.",
      link: "https://www.iobit.com/en/malware-fighter.php",
      section: "security",
    },
    {
      name: "Kaspersky TDSSKiller",
      description: "Rootkit remover",
      link: "https://usa.kaspersky.com/downloads/tdsskiller",
      section: "security",
    },
    {
      name: "KeePass",
      description: "Light-weight and easy-to-use password manager.",
      link: "https://keepass.info/",
      section: "security",
    },
    {
      name: "Malwarebytes Anti-Rootkit",
      description: "Rootkit killer.",
      link: "https://www.malwarebytes.com/antirootkit/",
      section: "security",
    },
    {
      name: "McAfee Stinger",
      description:
        "Standalone utility used to detect and remove specific viruses.",
      link:
        "https://www.mcafee.com/enterprise/en-gb/downloads/free-tools/stinger.html",
      section: "security",
    },
    {
      name: "pfSense",
      description: "Firewall software.",
      link: "https://www.pfsense.org/",
      section: "security",
    },
    {
      name: "PWGen",
      description: "Password generator",
      link: "https://pwgen-win.sourceforge.io/",
      section: "security",
    },
    {
      name: "Random Password Generator",
      description: "Password generator and manager.",
      link: "https://www.iobit.com/en/passwordgenerator.php",
      section: "security",
    },
    {
      name: "RoboForm",
      description: "Password manager.",
      link: "https://www.roboform.com/",
      section: "security",
    },
    {
      name: "Rootkit Removal",
      description: "Rootkit killer.",
      link:
        "https://www.sophos.com/en-us/products/free-tools/sophos-anti-rootkit.aspx",
      section: "security",
    },
    {
      name: "Spybot Free",
      description: "Spyware remover.",
      link: "https://www.safer-networking.org/",
      section: "security",
    },
    {
      name: "Superantispyware",
      description: "Spyware remover.",
      link: "https://www.superantispyware.com/",
      section: "security",
    },
    {
      name: "TDSSKiller",
      description: "Rootkit killer.",
      link: "https://support.kaspersky.com/5350",
      section: "security",
    },
    {
      name: "VeraCrypt",
      description: "Encryption tool.",
      link: "https://www.veracrypt.fr/en/Home.html",
      section: "security",
    },
    {
      name: "Wireshark",
      description:
        "World’s foremost and widely-used network protocol analyzer.",
      link: "https://www.wireshark.org/",
      section: "security",
    },
    {
      name: "Zip",
      description: "File archiver and compressor.",
      link: "https://www.7-zip.org/",
      section: "utilities",
    },
    {
      name: "All DLLs Dependencies",
      description: "Static analyzer for DLLs dependencies.",
      link: "http://jacquelin.potier.free.fr/AllDllDeps/",
      section: "utilities",
    },
    {
      name: "Ant Renamer",
      description: "Advanced file renaming utility.",
      link: "https://antp.be/software/renamer",
      section: "utilities",
    },
    {
      name: "Anti-Twin",
      description: "Delete duplicate files.",
      link: "http://www.anti-twin.com/",
      section: "utilities",
    },
    {
      name: "ArsClip",
      description: "Clipboard manager.",
      link: "http://www.joejoesoft.com/cms/showpage.php?cid=97",
      section: "utilities",
    },
    {
      name: "Autoruns",
      description: "Configure autorunning apps and more.",
      link: "https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns",
      section: "utilities",
    },
    {
      name: "Bart",
      description: "One-way file and folder synchronisation utility.",
      link: "https://www.zhornsoftware.co.uk/bart/index.html",
      section: "utilities",
    },
    {
      name: "BATExpert",
      description: "Crystal-clear vision of your laptop battery health status.",
      link: "https://kcsoftwares.com/?batexpert",
      section: "utilities",
    },
    {
      name: "BleachBit",
      description: "Clean your system and free disk space.",
      link: "https://www.bleachbit.org/",
      section: "utilities",
    },
    {
      name: "CCleaner",
      description: "Clean your PC from junk files.",
      link: "https://www.ccleaner.com/",
      section: "utilities",
    },
    {
      name: "Checksum Control",
      description: "A program to verify and write checksumfiles.",
      link: "https://sourceforge.net/projects/checksumcontrol/",
      section: "utilities",
    },
    {
      name: "Chocolatey",
      description: "Software updater and installer.",
      link: "https://chocolatey.org/",
      section: "utilities",
    },
    {
      name: "Classic Shell ",
      description:
        "Restores the classic Start menu for newer Windows versions.",
      link: "http://www.classicshell.net/",
      section: "utilities",
    },
    {
      name: "Clonezilla",
      description: "PC backup tool.",
      link: "https://clonezilla.org/",
      section: "utilities",
    },
    {
      name: "Converber",
      description: "Unit converter (converts units of measurement).",
      link: "http://www.xyntec.com/converber.htm",
      section: "utilities",
    },
    {
      name: "ConvertAll",
      description: "Unit converter (converts units of measurement).",
      link: "https://sourceforge.net/projects/convertall/",
      section: "utilities",
    },
    {
      name: "CPU-Z",
      description: "System profiler.",
      link: "https://www.cpuid.com/softwares/cpu-z.html",
      section: "utilities",
    },
    {
      name: "CrystalDiskInfo",
      description: "Disk health monitoring tool.",
      link: "https://crystalmark.info/en/software/crystaldiskinfo/",
      section: "utilities",
    },
    {
      name: "CrystalDiskMark",
      description: "Disk benchmark utility.",
      link: "https://crystalmark.info/en/software/crystaldiskmark/",
      section: "utilities",
    },
    {
      name: "Daphne",
      description: "Task manager replacement.",
      link: "http://www.drk.com.ar/daphne.php",
      section: "utilities",
    },
    {
      name: "DebugView",
      description: "System debug output monitor.",
      link: "https://docs.microsoft.com/en-us/sysinternals/downloads/debugview",
      section: "utilities",
    },
    {
      name: "Ditto",
      description: "Extension to the standard windows clipboard.",
      link: "https://ditto-cp.sourceforge.io/",
      section: "utilities",
    },
    {
      name: "Double Commander",
      description: "Two panel file manager.",
      link: "https://doublecmd.sourceforge.io/",
      section: "utilities",
    },
    {
      name: "DriveImage XML",
      description: "PC backup tool.",
      link: "https://www.runtime.org/driveimage-xml.htm",
      section: "utilities",
    },
    {
      name: "DropIt",
      description:
        "A flexible tool to automate processing and organizing files and folders.",
      link: "https://sourceforge.net/projects/dropit/",
      section: "utilities",
    },
    {
      name: "DShutdown",
      description:
        "Stand-alone program that allows you to easily shutdown and wake up local or remote PCs, with many specific options.",
      link: "http://dimio.altervista.org/eng/#DShutdown",
      section: "utilities",
    },
    {
      name: "DSynchronize",
      description: "Lets you periodically synchronize two or more folders.",
      link: "http://dimio.altervista.org/eng/#DSynchronize",
      section: "utilities",
    },
    {
      name: "DTaskManager",
      description: "Windows Task Manager replacement with extra functionality.",
      link: "http://dimio.altervista.org/eng/#DTaskManager",
      section: "utilities",
    },
    {
      name: "Dual Monitor Tools",
      description: "Tools for Windows users with dual or multiple monitors.",
      link: "https://sourceforge.net/projects/dualmonitortool/",
      section: "utilities",
    },
    {
      name: "DUMo",
      description:
        "Keeps your PC up-to-date and safe by using the most recent version of required hardware drivers.",
      link: "https://kcsoftwares.com/?dumo",
      section: "utilities",
    },
    {
      name: "Duplicate Cleaner",
      description: "Delete duplicate files.",
      link: "https://www.digitalvolcano.co.uk/duplicatecleaner.html",
      section: "utilities",
    },
    {
      name: "EaseUS Todo Backup",
      description: "PC backup tool.",
      link: "https://www.easeus.com/backup-software/tb-free.html",
      section: "utilities",
    },
    {
      name: "Everything",
      description: "Locate files and folders by name, instantly.",
      link: "https://www.voidtools.com/",
      section: "utilities",
    },
    {
      name: "Explorer++",
      description: "File manager.",
      link: "https://explorerplusplus.com/",
      section: "utilities",
    },
    {
      name: "Fast Duplicate File Finder",
      description: "Delete duplicate files.",
      link:
        "https://www.mindgems.com/products/Fast-Duplicate-File-Finder/Fast-Duplicate-File-Finder-Download.htm",
      section: "utilities",
    },
    {
      name: "FastCopy",
      description: "Copy and backup software.",
      link: "https://fastcopy.jp/en/",
      section: "utilities",
    },
    {
      name: "FileAlyzer",
      description: "Detailed file analysis.",
      link: "https://www.safer-networking.org/products/filealyzer/",
      section: "utilities",
    },
    {
      name: "FileVoyage",
      description: "Swiss Army Knife of file management.",
      link: "https://www.filevoyager.com/",
      section: "utilities",
    },
    {
      name: "Folding@home",
      description: "Computing project for simulating protein dynamics.",
      link: "https://foldingathome.org/",
      section: "utilities",
    },
    {
      name: "FontForge",
      description: "Font editor.",
      link: "https://fontforge.org/en-US/",
      section: "utilities",
    },
    {
      name: "FreeCommander",
      description:
        "Easy-to-use alternative to the standard windows file manager.",
      link: "https://freecommander.com/en/summary/",
      section: "utilities",
    },
    {
      name: "FreeFileSync",
      description: "Folder comparison and synchronization software.",
      link: "https://freefilesync.org/",
      section: "utilities",
    },
    {
      name: "FUPX",
      description:
        "Advanced graphical interface for the UPX (Ultimate Packer for eXecutables).",
      link: "http://www.pazera-software.com/products/free-upx/",
      section: "utilities",
    },
    {
      name: "GeekUninstaller",
      description: "Software uninstaller.",
      link: "https://geekuninstaller.com/",
      section: "utilities",
    },
    {
      name: "Ghostscript",
      description: "An interpreter for the PostScript language and for PDF.",
      link: "https://www.ghostscript.com/",
      section: "utilities",
    },
    {
      name: "GIMPS",
      description: "Overclocking tool.",
      link: "https://www.mersenne.org/",
      section: "utilities",
    },
    {
      name: "Glary",
      description: "Utility toolbox for enhancing computer performance.",
      link: "https://www.glarysoft.com/glary-utilities/",
      section: "utilities",
    },
    {
      name: "GParted",
      description: "Partition editor.",
      link: "https://gparted.org/",
      section: "utilities",
    },
    {
      name: "GPU-Z",
      description:
        "System utility designed to provide vital information about your video card and graphics processor.",
      link: "https://www.techpowerup.com/gpuz/",
      section: "utilities",
    },
    {
      name: "grepWin",
      description: "Search and replace using Regex (regular expressions).",
      link: "https://tools.stefankueng.com/grepWin.html",
      section: "utilities",
    },
    {
      name: "HDDExpert",
      description: "Crystal-clear vision of your Hard Drive (HDD or SSD).",
      link: "https://kcsoftwares.com/?hdde",
      section: "utilities",
    },
    {
      name: "HDHacker",
      description: "MBR and boot sector manager.",
      link: "http://dimio.altervista.org/eng/#HDHacker",
      section: "utilities",
    },
    {
      name: "HwiNFO",
      description:
        "Comprehensive hardware analysis, monitoring, and reporting.",
      link: "https://www.hwinfo.com/",
      section: "utilities",
    },
    {
      name: "IObit Undelete",
      description: "Deleted file recovery software.",
      link: "https://www.iobit.com/en/iobitundelete.php",
      section: "utilities",
    },
    {
      name: "IObit Uninstaller",
      description:
        "Software uninstaller with additional support for browser plug-ins.",
      link: "https://www.iobit.com/en/advanceduninstaller.php",
      section: "utilities",
    },
    {
      name: "KCleaner",
      description: "Hard disk cleaner.",
      link: "https://www.kcsoftwares.com/?kcleaner",
      section: "utilities",
    },
    {
      name: "IObit Unlocker",
      description: "Tool for unlocking file permissions.",
      link: "https://www.iobit.com/en/iobit-unlocker.php",
      section: "utilities",
    },
    {
      name: "Listary",
      description: "Search utility.",
      link: "https://www.listary.com/",
      section: "utilities",
    },
    {
      name: "Macrium Reflect",
      description: "Backup and restore tool.",
      link: "https://www.macrium.com/reflectfree",
      section: "utilities",
    },
    {
      name: "MemTest",
      description: "Memory diagnostics.",
      link: "https://www.memtest86.com/",
      section: "utilities",
    },
    {
      name: "MiniTool Partition Wizard",
      description: "Partition wizard.",
      link: "https://www.partitionwizard.com/free-partition-manager.html",
      section: "utilities",
    },
    {
      name: "MSI Afterburner",
      description: "Overclocking.",
      link: "https://www.msi.com/page/afterburner",
      section: "utilities",
    },
    {
      name: "MyPhoneExplorer",
      description: "Android smartphone sync software.",
      link: "https://www.fjsoft.at/en/",
      section: "utilities",
    },
    {
      name: "Ninite",
      description:
        "All-in-one software installer and updater. Great for initializing new PCs.",
      link: "https://ninite.com/",
      section: "utilities",
    },
    {
      name: "Open Hardware Monitor",
      description: "Hardware monitor.",
      link: "https://openhardwaremonitor.org/",
      section: "utilities",
    },
    {
      name: "Pandora Recovery",
      description: "Data recovery tool.",
      link: "https://www.pandorarecovery.com/",
      section: "utilities",
    },
    {
      name: "Paragon",
      description: "Backup and recovery tool.",
      link: "https://www.paragon-software.com/free/br-free/#",
      section: "utilities",
    },
    {
      name: "PCI-Z",
      description: "PCI devices profiler.",
      link: "https://www.pci-z.com/",
      section: "utilities",
    },
    {
      name: "PeaZip",
      description: "File archiver utility.",
      link: "https://www.peazip.org/",
      section: "utilities",
    },
    {
      name: "PhotoRec",
      description: "Data recovery tool.",
      link: "https://www.cgsecurity.org/wiki/PhotoRec",
      section: "utilities",
    },
    {
      name: "AppCompactor",
      description: "Shrink apps without affecting functionality.",
      link:
        "https://portableapps.com/apps/utilities/portableapps.com_appcompactor",
      section: "utilities",
    },
    {
      name: "PortExpert",
      description:
        "Gives you a detailed vision of your personnal computer cybersecurity",
      link: "https://kcsoftwares.com/?portexpert",
      section: "utilities",
    },
    {
      name: "Process Explorer",
      description: "Process explorer.",
      link:
        "https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer",
      section: "utilities",
    },
    {
      name: "Process Hacker",
      description:
        "Multi-purpose tool that helps you monitor system resources, debug software and detect malware.",
      link: "https://processhacker.sourceforge.io/",
      section: "utilities",
    },
    {
      name: "Process Monitor",
      description: "Advanced monitoring tool.",
      link: "https://docs.microsoft.com/en-us/sysinternals/downloads/procmon",
      section: "utilities",
    },
    {
      name: "Q-Dir",
      description: "Quad-pane file manager.",
      link: "http://www.softwareok.eu/?seite=Freeware/Q-Dir",
      section: "utilities",
    },
    {
      name: "QuickWayToFolders",
      description: "Provides quick folder content access.",
      link: "http://jacquelin.potier.free.fr/QuickWayToFolders/",
      section: "utilities",
    },
    {
      name: "RAMExpert",
      description: "Crystal-clear vision of your RAM.",
      link: "https://kcsoftwares.com/?ramexpert",
      section: "utilities",
    },
    {
      name: "RAMMap",
      description: "Physical memory usage analyzer.",
      link: "https://docs.microsoft.com/en-us/sysinternals/downloads/rammap",
      section: "utilities",
    },
    {
      name: "Rapid CRC Unicode",
      description: "CRC, MD5, and SHA hashing program.",
      link: "https://www.ov2.eu/programs/rapidcrc-unicode",
      section: "utilities",
    },
    {
      name: "Recuva",
      description: "Restore deleted files.",
      link: "https://www.ccleaner.com/recuva",
      section: "utilities",
    },
    {
      name: "Regshot",
      description: "Registry compare utility.",
      link: "https://sourceforge.net/projects/regshot/",
      section: "utilities",
    },
    {
      name: "ReNamer",
      description: "File renaming tool.",
      link: "https://www.den4b.com/products/renamer",
      section: "utilities",
    },
    {
      name: "Resource Hacker",
      description: "Resource compiler & decompiler.",
      link: "http://www.angusj.com/resourcehacker/",
      section: "utilities",
    },
    {
      name: "Revo Uninstaller",
      description: "Clean removal of any program from your PC.",
      link: "https://www.revouninstaller.com/",
      section: "utilities",
    },
    {
      name: "Rufus",
      description: "Creates bootable USB drives.",
      link: "https://rufus.ie/",
      section: "utilities",
    },
    {
      name: "SearchMyFiles",
      description: "Deletes duplicate files.",
      link: "http://www.nirsoft.net/utils/search_my_files.html",
      section: "utilities",
    },
    {
      name: "ShareIt",
      description: "Cross-platform file transfer software.",
      link: "https://shareit.one/",
      section: "utilities",
    },
    {
      name: "Shortcuts Search And Replace",
      description: "Allows to do easy operations on shortcuts.",
      link: "http://jacquelin.potier.free.fr/ShortcutsSearchAndReplace/",
      section: "utilities",
    },
    {
      name: "SIW (System Information for Windows)",
      description:
        "Tool to analyse your computer and gather detailed information about system properties and settings.",
      link: "https://www.gtopala.com/",
      section: "utilities",
    },
    {
      name: "Smart Defrag",
      description: "Disk defragmentation and optimization.",
      link: "https://www.iobit.com/en/iobitsmartdefrag.php",
      section: "utilities",
    },
    {
      name: "SpaceSniffer",
      description: "Hard disk space usage analyzer.",
      link: "http://www.uderzo.it/main_products/space_sniffer/",
      section: "utilities",
    },
    {
      name: "Speccy",
      description:
        "Fast, lightweight, advanced system information tool for your PC.",
      link: "https://www.ccleaner.com/speccy",
      section: "utilities",
    },
    {
      name: "SSD-Z",
      description: "SSD information tool.",
      link: "http://aezay.dk/aezay/ssdz/",
      section: "utilities",
    },
    {
      name: "Startup Delayer",
      description: "Optimizes your startup process.",
      link: "https://www.r2.com.au/page/products/show/startup-delayer/",
      section: "utilities",
    },
    {
      name: "Startup Sentinel",
      description: "Faster and more secure startup.",
      link: "https://kcsoftwares.com/?sus",
      section: "utilities",
    },
    {
      name: "SUMo",
      description:
        "Keeps your PC up-to-date and safe by using the most recent version of your favorite software.",
      link: "https://kcsoftwares.com/?sumo",
      section: "utilities",
    },
    {
      name: "SyncBackFree",
      description: "Backup and synchronize your disc.",
      link: "https://www.2brightsparks.com/freeware/freeware-hub.html",
      section: "utilities",
    },
    {
      name: "Synkron",
      description: "File and directory synchronization.",
      link: "http://synkron.sourceforge.net/",
      section: "utilities",
    },
    {
      name: "System Explorer",
      description:
        "Software for exploration and management of system internals.",
      link: "http://systemexplorer.net/",
      section: "utilities",
    },
    {
      name: "TeamViewer",
      description:
        "Remote desktop software for troubleshooting and collaboration.",
      link: "https://www.teamviewer.com/en/",
      section: "utilities",
    },
    {
      name: "TestDisk",
      description:
        "Recover lost partitions and/or make non-booting disks bootable again.",
      link: "https://www.cgsecurity.org/wiki/TestDisk",
      section: "utilities",
    },
    {
      name: "TidyTabs",
      description: "Tool that brings tabbed browsing to all of your programs.",
      link: "https://www.nurgo-software.com/products/tidytabs",
      section: "utilities",
    },
    {
      name: "TightVNC",
      description: "Remote desktop software.",
      link: "https://www.tightvnc.com/",
      section: "utilities",
    },
    {
      name: "TinyTask",
      description: "Simple tool for playback and recording of macros.",
      link: "https://tinytask.en.lo4d.com/windows",
      section: "utilities",
    },
    {
      name: "Total Commander",
      description: "Two panel file manager.",
      link: "https://www.ghisler.com/",
      section: "utilities",
    },
    {
      name: "TreeSize Free",
      description: "Disk usage analyzer and cleanup tool.",
      link: "https://www.jam-software.com/treesize_free",
      section: "utilities",
    },
    {
      name: "Turn Off Xbox 360 Controller",
      description: "Turns off - you guessed it! - your Xbox 360 controller.",
      link: "https://sourceforge.net/projects/turnoffxboxcontroller/",
      section: "utilities",
    },
    {
      name: "TyperTask",
      description: "Instant word expansion, keyboard shortcuts and macros.",
      link:
        "https://www.nch.com.au/fastfox/index.html?kw=typertask&gclid=EAIaIQobChMIz7q3hN_86QIVQYBQBh0QiwViEAAYASAAEgIe2fD_BwE",
      section: "utilities",
    },
    {
      name: "Ultra VNC",
      description: "Remote desktop software.",
      link: "https://www.uvnc.com/",
      section: "utilities",
    },
    {
      name: "UltraDefrag",
      description: "Disk defragmentation of locked system files.",
      link: "https://sourceforge.net/projects/ultradefrag/",
      section: "utilities",
    },
    {
      name: "Undelete 360",
      description: "Data recovery tool.",
      link: "http://www.undelete360.com/",
      section: "utilities",
    },
    {
      name: "Unetbootin",
      description:
        "Creates bootable USB drives, with support for automatic download of popular Linux distros.",
      link: "https://unetbootin.github.io/",
      section: "utilities",
    },
    {
      name: "Virtual Volumes View",
      description:
        "Catalogs the content of removable volumes like CD and DVD disks for off-line searching.",
      link: "http://vvvapp.sourceforge.net/",
      section: "utilities",
    },
    {
      name: "VirtualBox",
      description: "Virtualization software.",
      link: "https://www.virtualbox.org/",
      section: "utilities",
    },
    {
      name: "VirtuaWin",
      description: "Virtual desktop manager.",
      link: "https://virtuawin.sourceforge.io/",
      section: "utilities",
    },
    {
      name: "VMMap",
      description: "Virtual and physical memory analysis utility.",
      link: "https://docs.microsoft.com/en-us/sysinternals/downloads/vmmap",
      section: "utilities",
    },
    {
      name: "WFDownloader",
      description:
        "Multipurpose bulk downloader and cross-platform bulk image downloader.",
      link: "https://www.wfdownloader.xyz/",
      section: "utilities",
    },
    {
      name: "WhatChanged",
      description:
        "Simple utility that searches for modified files and registry entries.",
      link: "https://www.majorgeeks.com/files/details/what_changed.html",
      section: "utilities",
    },
    {
      name: "WinAPIOverride",
      description: "Advanced API monitoring software.",
      link: "http://jacquelin.potier.free.fr/winapioverride32/",
      section: "utilities",
    },
    {
      name: "WinDirStat",
      description: "Disk usage statistics viewer and cleanup tool.",
      link: "https://windirstat.net/",
      section: "utilities",
    },
    {
      name: "Windows Error Lookup Tool",
      description: "Find windows error code details.",
      link: "https://www.microsoft.com/en-us/download/details.aspx?id=100432",
      section: "utilities",
    },
    {
      name: "WinFLASHTool",
      description: "Allows writing raw disk images to FLASH memory cards.",
      link: "https://sysprogs.com/winflashtool/",
      section: "utilities",
    },
    {
      name: "WinMD5Free",
      description: "Tiny and fast utility to compute MD5 hash value for files.",
      link: "https://www.winmd5.com/",
      section: "utilities",
    },
    {
      name: "WinMerge",
      description: "Open-source diffing and merging tool.",
      link: "https://winmerge.org/?lang=en",
      section: "utilities",
    },
    {
      name: "WinMTR",
      description:
        "Combines the functionality of the traceroute and ping in a single network diagnostic tool.",
      link: "https://sourceforge.net/projects/winmtr/",
      section: "utilities",
    },
    {
      name: "Workrave",
      description:
        "Program that assists in the recovery and prevention of Repetitive Strain Injury (RSI).",
      link: "https://sourceforge.net/projects/workrave/",
      section: "utilities",
    },
    {
      name: "XN Resource Editor",
      description: "Binary resource editor.",
      link: "https://stefansundin.github.io/xn_resource_editor/",
      section: "utilities",
    },
    {
      name: "Xpy",
      description: "System settings tweaker.",
      link: "https://sourceforge.net/projects/xpy/",
      section: "utilities",
    },
    {
      name: "YUMI-UEFI",
      description: "Multiboot USB creator.",
      link: "https://www.pendrivelinux.com/yumi-multiboot-usb-creator/",
      section: "utilities",
    },
    {
      name: "Zint Barcode Studio",
      description: "Barcode generator.",
      link: "https://zint.github.io/",
      section: "utilities",
    },
    {
      name: "ZIP Archiver",
      description:
        "A free program for compressing and opening ZIP, RAR, TAR, and 7Z files.",
      link: "http://ziparchiver.hamstersoft.com/",
      section: "utilities",
    },
    {
      name: "ZSoft Uninstaller",
      description: "Uninstaller and cleaner.",
      link: "https://www.zsoft.dk/index/software_details/4",
      section: "utilities",
    },
    {
      name: "CutePDF Editor",
      description: "Free online PDF editor.",
      link: "https://www.cutepdf-editor.com/default.asp",
      section: "online",
    },
    {
      name: "myNoise",
      description:
        "Background noises and interactive soundscapes. Great for both relaxation and productivity.",
      link: "https://mynoise.net/",
      section: "online",
    },
    {
      name: "TotalVirus",
      description:
        "Online virus scanner that checks your software against many different scanning engines.",
      link: "http://www.virustotal.com/",
      section: "online",
    },
    {
      name: "Befunky",
      description: "Online photo editor.",
      link: "https://www.befunky.com/",
      section: "online",
    },
    {
      name: "Cymath",
      description: "Mathematical equations solver.",
      link: "https://www.cymath.com/",
      section: "online",
    },
    {
      name: "Desmos",
      description: "Online calculator.",
      link: "https://www.desmos.com/",
      section: "online",
    },
    {
      name: "Draw.io",
      description: "Online diagram creation software",
      link: "https://www.draw.io/",
      section: "online",
    },
    {
      name: "DropSend",
      description: "Online file transfer.",
      link: "https://www.dropsend.com/",
      section: "online",
    },
    {
      name: "Duolingo",
      description: "Free tool for learning new languages.",
      link: "https://www.duolingo.com/",
      section: "online",
    },
    {
      name: "fxSolver",
      description: "Solver for engineering and scientific equations.",
      link: "https://www.fxsolver.com/",
      section: "online",
    },
    {
      name: "Google Docs",
      description: "Free online office suite.",
      link: "https://www.google.co.uk/docs/about/",
      section: "online",
    },
    {
      name: "Google Translate",
      description: "AI-based translator.",
      link: "https://translate.google.com/",
      section: "online",
    },
    {
      name: "Internet Archive",
      description:
        "Library of millions of free books, movies, software, music, websites, and more.",
      link: "https://archive.org/",
      section: "online",
    },
    {
      name: "Majorgeeks",
      description: "Free software database. Sounds kinda familiar but idk",
      link: "https://www.majorgeeks.com/",
      section: "online",
    },
    {
      name: "Mathway",
      description:
        "Solver for mathematical equations, chemistry equations, and more.",
      link: "https://www.mathway.com/",
      section: "online",
    },
    {
      name: "Microsoft Terminology Translator",
      description: "Translator for software terminology.",
      link: "https://www.microsoft.com/en-us/language/search",
      section: "online",
    },
    {
      name: "Microsoft Docs",
      description:
        "Microsoft documentation for end users, developers and IT professionals.",
      link: "https://docs.microsoft.com/",
      section: "online",
    },
    {
      name: "OnlineTechTips",
      description: "Tech tips, online.",
      link: "https://www.online-tech-tips.com/",
      section: "online",
    },
    {
      name: "pCloudTransfer",
      description: "Online file transfer.",
      link: "https://transfer.pcloud.com/",
      section: "online",
    },
    {
      name: "Pixlr",
      description: "Online photo editor.",
      link: "https://pixlr.com/",
      section: "online",
    },
    {
      name: "Poly",
      description: "Creators can browse, share and download 3D models.",
      link: "https://poly.google.com/",
      section: "online",
    },
    {
      name: "Reddit",
      description:
        "Massive online forum with sub-communities (subreddits) for alomst any topic imaginable.",
      link: "https://www.reddit.com/",
      section: "online",
    },
    {
      name: "SourceForge",
      description: "Open-source business and software platform.",
      link: "https://sourceforge.net/",
      section: "online",
    },
    {
      name: "VideoHelp",
      description: "Audio and video website with a lot of free software",
      link: "https://www.videohelp.com/",
      section: "online",
    },
    {
      name: "WeTransfer",
      description: "Online file transfer.",
      link: "https://wetransfer.com/",
      section: "online",
    },
    {
      name: "Wunderlist",
      description: "To-do manager.",
      link: "https://www.wunderlist.com/",
      section: "online",
    },
    {
      name: "Akinator",
      description:
        "20 Questions, with an exclusive focus on people (real or fictional).",
      link: "https://akinator.com/",
      section: "cheer",
    },
    {
      name: "Bored Button™",
      description: "For boredom.",
      link: "https://www.boredbutton.com/",
      section: "cheer",
    },
    {
      name: "Discuvver",
      description: "Random useful sites in your inbox weekly.",
      link: "https://www.discuvver.com/",
      section: "cheer",
    },
    {
      name: "Find the Invisible Cow",
      description: "Go ahead; find it.",
      link: "https://findtheinvisiblecow.com/",
      section: "cheer",
    },
    {
      name: "Geek Typer",
      description: "Mash your keyboard to hack. You hacker, you.",
      link: "https://geektyper.com/",
      section: "cheer",
    },
    {
      name: "Google Gravity",
      description: "Newton's law of universal graviation; applied.",
      link: "https://mrdoob.com/projects/chromeexperiments/google-gravity/",
      section: "cheer",
    },
    {
      name: "Google Space",
      description: "Gravity-free Google.",
      link: "https://mrdoob.com/projects/chromeexperiments/google-space/",
      section: "cheer",
    },
    {
      name: "Hacker Typer",
      description: "Mash your keyboard to hack. You hacker, you.",
      link: "http://hackertyper.com/",
      section: "cheer",
    },
    {
      name: "Museum of Endangered Sounds",
      description: "Relive the sounds of the past.",
      link: "http://savethesounds.info/",
      section: "cheer",
    },
    {
      name: "Online Tone Generator",
      description: "Generate tones - online!",
      link: "http://onlinetonegenerator.com/",
      section: "cheer",
    },
    {
      name: "Pointer Pointer",
      description: "Points at your pointer.",
      link: "https://pointerpointer.com/",
      section: "cheer",
    },
    {
      name: "Quick Draw",
      description: "WarioWare-style drawing game.",
      link: "https://quickdraw.withgoogle.com/#",
      section: "cheer",
    },
    {
      name: "Radio Garden",
      description: "Explore live radio by rotating the globe.",
      link: "http://radio.garden/",
      section: "cheer",
    },
    {
      name: "Radiooooo",
      description: "A musical time machine.",
      link: "https://radiooooo.com/",
      section: "cheer",
    },
    {
      name: "Slither.io",
      description: "A massively multiplayer online SPG (Snake Playing Game).",
      link: "http://slither.io/",
      section: "cheer",
    },
    {
      name: "Staggering Beauty",
      description: "Psychadelic!",
      link: "http://www.staggeringbeauty.com/",
      section: "cheer",
    },
    {
      name: "Useless Website",
      description:
        "useless (adj.) - not fulfilling or not expected to achieve the intended purpose or desired outcome.",
      link: "https://theuselessweb.com/",
      section: "cheer",
    },
    {
      name: "Weavesilk",
      description: "Interactive generative art.",
      link: "http://weavesilk.com/",
      section: "cheer",
    },
    {
      name: "You're Getting Old",
      description: "Discover your own mortality!",
      link: "https://you.regettingold.com/",
      section: "cheer",
    },
  ],
};
